# Generated by Django 5.2 on 2025-11-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={"ordering": ["order", "-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="module",
            options={"ordering": ["order", "-created_at"]},
        ),
        migrations.AlterUniqueTogether(
            name="module",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="course",
            name="est_duration",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="content",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="content_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="estimated_duration",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="module",
            name="estimated_duration",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="module",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
    ]
