# Generated by Django 5.2 on 2025-11-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="cover_image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
