# Generated by Django 5.2 on 2025-11-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0002_alter_course_cover_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="cover_image",
            field=models.URLField(
                blank=True,
                default="https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=800&h=450&fit=crop",
                max_length=500,
            ),
        ),
    ]
