# Generated by Django 5.2 on 2025-11-28 08:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0003_alter_course_cover_image"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="lesson",
            unique_together=set(),
        ),
    ]
