# Generated by Django 5.2 on 2025-11-28 08:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0004_remove_lesson_order_unique_constraint"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={"ordering": ["module", "order", "created_at"]},
        ),
        migrations.AlterModelOptions(
            name="module",
            options={"ordering": ["course", "order", "created_at"]},
        ),
    ]
