# Generated by Django 5.2 on 2025-11-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_activities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="progress_percent",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="moduleprogress",
            name="progress_percent",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
